export const feed = `
<?xml version="1.0"?>
<!-- RSS generated by Radio UserLand v8.0.5 on 9/30/2002; 4:00:00 AM Pacific -->
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:blogChannel="http://backend.userland.com/blogChannelModule">
	<channel>
		<title>Scripting News</title>
		<link>http://www.scripting.com/</link>
		<description>A weblog about scripting and stuff like that.</description>
		<language>en-us</language>
		<blogChannel:blogRoll>http://radio.weblogs.com/0001015/userland/scriptingNewsLeftLinks.opml</blogChannel:blogRoll>
		<blogChannel:mySubscriptions>http://radio.weblogs.com/0001015/gems/mySubscriptions.opml</blogChannel:mySubscriptions>
		<blogChannel:blink>http://diveintomark.org/</blogChannel:blink>
		<copyright>Copyright 1997-2002 Dave Winer</copyright>
		<lastBuildDate>Mon, 30 Sep 2002 11:00:00 GMT</lastBuildDate>
		<docs>http://backend.userland.com/rss</docs>
		<generator>Radio UserLand v8.0.5</generator>
		<category domain="Syndic8">1765</category>
		<managingEditor>dave@userland.com</managingEditor>
		<webMaster>dave@userland.com</webMaster>
		<dc:publisher>dave@userland.com</dc:publisher>
    <dc:creator>dave@userland.com (Dave Winer)</dc:creator>
    <dc:rights>Copyright 1997-2002 Dave Winer</dc:rights>
    <dc:date>2002-09-29T11:13:01-07:00</dc:date>
		<ttl>40</ttl>
		<item>
			<description>Monday's baseball games are on the &lt;a href="http://www.allstarsoftware.net/homeschedule.htm"&gt;schedule&lt;/a&gt;.</description>
			<dc:creator>paul@userland.com (Paul Prescod)</dc:creator>
      <enclosure url="http://www.scripting.com/mp3s/weatherReportSuite.mp3" length="12216320" type="audio/mpeg" />
			<guid isPermaLink="false">http://scriptingnews.userland.com/backissues/2002/09/29#When:6:56:02PM</guid>
			<pubDate>Mon, 30 Sep 2002 01:56:02 GMT</pubDate>
		</item>
	</channel>
</rss>
`;
