export const feed = `
<?xml version="1.0"?>
<!-- RSS generated by Radio UserLand v8.0.5 on 9/30/2002; 4:00:00 AM Pacific -->
<rss version="2.0" xmlns:blogChannel="http://backend.userland.com/blogChannelModule">
	<channel>
		<title>Scripting News</title>
		<link>http://www.scripting.com/</link>
		<link>http://www.scripting2.com/</link>
		<description>A weblog about scripting and stuff like that.</description>
		<language>en-us</language>
		<blogChannel:blogRoll>http://radio.weblogs.com/0001015/userland/scriptingNewsLeftLinks.opml</blogChannel:blogRoll>
		<blogChannel:mySubscriptions>http://radio.weblogs.com/0001015/gems/mySubscriptions.opml</blogChannel:mySubscriptions>
		<blogChannel:blink>http://diveintomark.org/</blogChannel:blink>
		<copyright>Copyright 1997-2002 Dave Winer</copyright>
		<lastBuildDate>Mon, 30 Sep 2002 11:00:00 GMT</lastBuildDate>
		<docs>http://backend.userland.com/rss</docs>
		<generator>Radio UserLand v8.0.5</generator>
		<category domain="Syndic8">1765</category>
		<managingEditor>dave@userland.com</managingEditor>
		<webMaster>dave@userland.com</webMaster>
		<image>
			<title>test image</title>
			<url>http://www.example.com/image.jpg</url>
		</image>
		<ttl>40</ttl>
		<skipHours>
			<hour>6</hour>
			<hour>7</hour>
			<hour>8</hour>
			<hour>9</hour>
			<hour>10</hour>
			<hour>11</hour>
		</skipHours>
		<item>
			<description>Monday's baseball games are on the &lt;a href="http://www.allstarsoftware.net/homeschedule.htm"&gt;schedule&lt;/a&gt;.</description>
			<enclosure url="http://www.scripting.com/mp3s/weatherReportSuite.mp3" length="12216320" type="audio/mpeg" />
			<guid isPermaLink="false">http://scriptingnews.userland.com/backissues/2002/09/29#When:6:56:02PM</guid>
			<pubDate>Mon, 30 Sep 2002 01:56:02 GMT</pubDate>
		</item>
		<item>
			<description>Josh Kirby, creator of the &lt;a href="http://www.amazon.com/exec/obidos/tg/detail/-/0441008690/qid=1033404393/sr=8-1/ref=sr_8_1/002-3507671-0351252?v=glance&amp;n=507846"&gt;Discworld book covers&lt;/a&gt;, died at age 61. What a shame, his art was one of the best reasons to read the books.</description>
			<guid isPermaLink="false">http://scriptingnews.userland.com/backissues/2002/09/29#When:6:52:49PM</guid>
			<pubDate>Sun, 29 Sep 2002 19:59:01 GMT</pubDate>
		</item>
		<item>
			<description>Listening to &lt;a href="http://www.ukogbani.org/php/app.php?a=bio&amp;b=a016"&gt;Charles McLaughlin&lt;/a&gt; on the &lt;a href="http://www.kpig.com/"&gt;KPIG&lt;/a&gt; Sunday morning folk show. Very spacey. &lt;i&gt;"How does it feel to be loved by him?"&lt;/i&gt;</description>
			<guid isPermaLink="false">http://scriptingnews.userland.com/backissues/2002/09/29#When:3:59:56PM</guid>
			<pubDate>Sun, 29 Sep 2002 10:59:56 GMT</pubDate>
		</item>
		<item>
			<description>&lt;a href="http://espn.go.com/"&gt;ESPN&lt;/a&gt; is running a &lt;a href="http://espn.go.com/mlb/s/2002/0928/1439324.html"&gt;sweet article&lt;/a&gt; about the Giants, focusing on Dusty Baker and Jeff Kent. Both may be gone next year which would be a real shame. Both are really great guys. Dusty is a hero to the community, he's always helping with cancer victims, sick kids, the homeless. If he goes a piece of San Francisco will be missing. And Jeff Kent is a man's man, a guy who &lt;a href="http://espn.go.com/mlb/s/2002/0929/1439583.html"&gt;plays even when he's injured&lt;/a&gt;, like he was in the 2000 playoffs. Not sure if he was injured in the 2002 division-winning game, but it wouldn't surprise me at all. (PS I'm pretty sure Kent was playing with an injury in the 9th inning yesterday.) The Bay Area press doesn't cover these guys as the heroes they are. The injuries are all part of the baseball ethos that fans don't hear about much.</description>
			<guid isPermaLink="false">http://scriptingnews.userland.com/backissues/2002/09/29#When:3:09:21PM</guid>
			<pubDate>Sun, 29 Sep 2002 21:56:02 GMT</pubDate>
		</item>
		<item>
			<description>&lt;a href="http://www.thetwowayweb.com/paymentSystems"&gt;Payment systems&lt;/a&gt; are on-topic.</description>
			<guid isPermaLink="false">http://scriptingnews.userland.com/backissues/2002/09/29#When:6:47:44AM</guid>
			<pubDate>Sun, 29 Sep 2002 13:47:44 GMT</pubDate>
		</item>
		<item>
			<description>BTW, for those who were scared for me last night, thanks for your concern. I'm fine.</description>
			<guid isPermaLink="false">http://scriptingnews.userland.com/backissues/2002/09/29#When:6:47:05AM</guid>
			<pubDate>Sun, 29 Sep 2002 13:47:05 GMT</pubDate>
		</item>
		<item>
			<description>If you use a centralized identity system, I can use the identity information in ways you can't control. For example, I can associate the name "Bob Smith" with a weblog that says something critical about someone named Bob Smith. Then when Bob searches for his name using Google, the criticism comes up as a hit. Then consider the case where I know 10 people named "Bob Smith" so I do this 10 times. In all cases I gather the information from a centralized identity system, and from search engines. Bottom-line &lt;a href="http://www.gotfuturama.com/Multimedia/Sounds/Bender/arrogant.wav"&gt;humans should not trust computers&lt;/a&gt; to keep information about them in confidence, it's always available for exploitation in ways you can't control.</description>
			<guid isPermaLink="false">http://scriptingnews.userland.com/backissues/2002/09/29#When:6:40:49AM</guid>
			<pubDate>Sun, 29 Sep 2002 13:40:49 GMT</pubDate>
		</item>
		<item>
			<description>&lt;a href="http://icfcst.kiev.ua/panorama/siege.html"&gt;Siege&lt;/a&gt; is a puzzle game that's unique, clever, and works in most browsers.</description>
			<guid isPermaLink="false">http://scriptingnews.userland.com/backissues/2002/09/29#When:4:07:57AM</guid>
			<pubDate>Sun, 29 Sep 2002 11:07:57 GMT</pubDate>
		</item>
		<item>
			<description>Rick Smolan, the creator of A Day in the Life of America is &lt;a href="http://www.efn.org/~hkrieger/s017.htm"&gt;working on a new project&lt;/a&gt;. &lt;i&gt;"Hello, I'm working with National Geographic, Kodak and the Turkish Tourist Bureau on a large-scale Internet photography project and I would like to speak with you about it."&lt;/i&gt;</description>
			<guid isPermaLink="false">http://scriptingnews.userland.com/backissues/2002/09/29#When:3:50:18AM</guid>
			<pubDate>Sun, 29 Sep 2002 10:50:18 GMT</pubDate>
		</item>
	</channel>
</rss>
`;
